### ISSUE TITLE
My personal Flickr API does not work

### ISSUE THREAD

**Issue by piyota** [hellopablo/simpl-flickr-slidr#1]
Hi, thank you so much for developing this. I just substitute my Flickr API and object ID but the slide does not show up. I don't really know what's wrong with my API. Your supplied API works just fine. I have set all my settings as public. Thanks again.

**Comment by hellopablo** [comment]
Hey,

Sorry you're having issues! To be honest, this plugin was written in a hurry a long time ago. I've made a note to try and rewrite/look at this, but I'm exceptionally busy at work just now so might be a while before I can take a break and visit this!

It may well be that the Flickr API has changed somehow.

P.
